networks: # Define the network(s) here
  backend-network: # Define the backend network
    driver: bridge # Use an existing network
services:
  backend:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:${MYSQL_ROOT_PASSWORD}@db/flask_app
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=http://localhost:3000
    depends_on: # ensures db container starts before the backend container
      - db
    networks:
      - backend-network
    restart: on-failure
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Use environment variable for password
      - MYSQL_DATABASE=flask_app
    volumes:
      - db_data:/var/lib/mysql # Persist the database across container restarts
    ports:
      - "3306:3306"
    restart: always 
    networks:
      - backend-network
volumes:
  db_data:
